---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      name: springboot-pod
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot-container
          image: jaisai0506/my-springboot-app:v1  # ✅ your Docker Hub image
          ports:
            - containerPort: 8080                # ✅ change if your app uses another port
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: LoadBalancer
  selector:
    app: springboot
  ports:
    - port: 80
      targetPort: 8080
